### ISSUE TITLE
Bug in README?

### ISSUE THREAD

**Issue by SenyorDrew** [alchemab/parapred-pytorch#2]
Hi,
Thanks for putting together a great resource.  I was wondering if there's a bug in the README on how to integrate into a larger python codebase:

Should the statement:
`encoded, lengths = encode_batch(sequences, max_length = 40)`
instead be:
`encoded, lengths = encode_batch(sorted_cdr_strings, max_length = 40)`

since sequences is unsorted and pytorch requires that the array be sorted.

Thanks

**Comment by jleem-iso** [comment]
Yes, good point – thanks. 

There was something about length sorting that I remember fiddling around with, and I don't think I got around to updating everything, especially the docs. Will update on the next release though!

**Comment by jleem-iso** [comment]
Sorry this took ages, somehow got lost in the ether then I remembered to fix!
